### ISSUE TITLE
不太懂laravel，请问如何部署，如何修改配置

### ISSUE THREAD

**Issue by ifwangs** [hldh214/gas#4]

**Comment by hldh214** [comment]
因为 master 分支是公众号版本, 如果只是想看看代码可以去 [legacy](https://github.com/hldh214/gas/tree/lagacy) 分支瞧一瞧

**Comment by ifwangs** [comment]
我自己有个公众号，目前部署的legacy版本，想增加个图片搜索功能，我的公众号是私人使用，不会滥用

**Comment by hldh214** [comment]
大致步骤先 clone 到本地, composer 装一下依赖, 配置一下 .env 文件
可以参考这里 https://github.com/overtrue/laravel-wechat

**Comment by ifwangs** [comment]
部署好了，env文件也配置好了。但是在公众平台无论token填写啥都通过，而且也不会自动回复微信消息

**Comment by ifwangs** [comment]
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:sgSSPaRCUFA4JvWWIiVtRu6B2dDUviSfGhFxr0Q5lPk=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

WECHAT_LOG_LEVEL=
WECHAT_OFFICIAL_ACCOUNT_APPID=wssdsad8b4608bb3945
WECHAT_OFFICIAL_ACCOUNT_SECRET=fdadsca9b32abbe44270b00e0227b0a
WECHAT_OFFICIAL_ACCOUNT_TOKEN=jlibccc
WECHAT_OFFICIAL_ACCOUNT_AES_KEY=XLIMFsasasaasbkiPsgfD5pv5MbVcrZ3GlBmxbwNOqr4I

JAVBUS_BASE_URL=
TIMEOUT=

您看还需要改其他地方吗

**Comment by ifwangs** [comment]
![snipaste20180703_212119](https://user-images.githubusercontent.com/7021399/42222228-1d6f68cc-7f07-11e8-8667-e831f0b891b4.jpg)

**Comment by ifwangs** [comment]
![snipaste20180703_214211](https://user-images.githubusercontent.com/7021399/42223302-0add7f52-7f0a-11e8-89c2-87701125fe9d.jpg)

**Comment by ifwangs** [comment]
wechat.log文件
![snipaste20180703_224758](https://user-images.githubusercontent.com/7021399/42227084-43fcffe8-7f13-11e8-875e-20f4919b7b6a.jpg)

**Comment by ifwangs** [comment]
wechat日志文件
![snipaste20180703_224953](https://user-images.githubusercontent.com/7021399/42227198-842a08fe-7f13-11e8-98e4-d72b48323e2b.jpg)

**Comment by hldh214** [comment]
我没遇到这种情况, 不过看你的 wechat 日志倒数第二行的报错就知道应该是 guzzleHTTP 这个库出问题了
`a non-numeric value encountered guzzlehttp` 这玩意, 你 Google 一下看能不能找到什么线索
另外你说一下你 php 版本, 这些依赖都是 `composer install` 安装的吗

**Comment by ifwangs** [comment]
php7.2版，是用composer安装的依赖

**Comment by ifwangs** [comment]
可以了，就是回复#获取随机还会报错。wechat日志
[2018-07-04 12:14:50] NULL.ERROR: 0: mt_rand(): max(-1) is smaller than min(0) {"code":0,"message":"mt_rand(): max(-1) is smaller than min(0)","file":"/www/wwwroot/jlib.wyaoyao.cn/app/Http/Controllers/JLibController.php","line":391} 
[2018-07-04 12:14:50] NULL.DEBUG: Server response created: {"content":"success"}

**Comment by hldh214** [comment]
奥 这个是我的问题 我没写 README
你在项目根目录执行 `php artisan crawl` 就好啦
这命令可能会耗时 5~10 分钟, 如果出现网络问题报错了就得重新再执行直到命令自然退出就好啦

**Comment by hldh214** [comment]
详细可以看这里 https://github.com/hldh214/gas/blob/master/app/Console/Commands/Crawl.php

**Comment by ifwangs** [comment]
搞定，麻烦了
