### ISSUE TITLE
卡住了呀，大胸dei

### ISSUE THREAD

**Issue by dingpamaoo** [hldh214/gas#5]
![image](https://user-images.githubusercontent.com/8704246/44972019-4bfcb380-af8a-11e8-8767-2c1e012c6c20.png)
一直卡在loading这里

**Comment by hldh214** [comment]
你这是自己搭的服务器吗, 可以 F12 看看网络请求

dingpamaoo <notifications@github.com> 于2018年9月3日周一 下午3:02写道：
